<?php
const Rule = [
    '链接地址' => [
        'name' => '获取',
        'type' => -1,
        'url' => '[url]/ajax.php?act=LinkExtraction',
        'way' => 1,
        'placeholder' => '请输入带有链接的信息',
    ],
    '图片链接' => [
        'name' => '上传图片',
        'type' => 2,
        'url' => '[url]/ajax.php?act=Decode',
        'way' => 1,
        'placeholder' => '请点击旁边的按钮上传需要解析的图片',
    ],
    '说说ID|说说id' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=SSID',
        'way' => 2,
        'placeholder' => '请在上方输入框内填写好QQ，然后点击获取！',
    ],
    '收货地址' => [
        'name' => '选择收货地址',
        'type' => 1,
        'way' => 1,
        'placeholder' => '请将收货地址信息填写完整哦！',
    ],
    '火山ＩＤ|火山视频ID' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=HSID',
        'way' => 1,
        'placeholder' => '在此输入火山视频的链接,然后点击获取按钮！',
    ],
    '微视ＩＤ|微视作品ID' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=WSID',
        'way' => 1,
        'placeholder' => '在此输入微视的作品链接,然后点击获取按钮！',
    ],
    '头条ID|头条ＩＤ' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=JRTTID',
        'way' => 1,
        'placeholder' => '在此输入今日头条的链接,然后点击获取按钮！',
    ],
    '皮皮虾ID' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=PPXID',
        'way' => 1,
        'placeholder' => '在此输入链接,然后点击获取按钮！',
    ],
    '小红书ID' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=XHSID',
        'way' => 1,
        'placeholder' => '在此输入链接,然后点击获取按钮！',
    ],
    '美拍ID|美拍ＩＤ' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=MPID',
        'way' => 1,
        'placeholder' => '在此输入链接,然后点击获取按钮！',
    ],
    '哔哩哔哩ID|哔哩视频ID' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=BLIID',
        'way' => 1,
        'placeholder' => '在此输入链接,然后点击获取按钮！',
    ],
    '最右帖子ID' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=ZYOUID',
        'way' => 1,
        'placeholder' => '在此输入链接,然后点击获取按钮！',
    ],
    '全民K歌ID|全民ID' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=QMKGID',
        'way' => 1,
        'placeholder' => '在此输入链接,然后点击获取按钮！',
    ],
    '美图作品ID|美图视频ID' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=MTXXID',
        'way' => 1,
        'placeholder' => '在此输入链接,然后点击获取按钮！',
    ],
    '绿洲作品ID|绿洲视频ID' => [
        'name' => '获取ID',
        'type' => -1,
        'url' => '[url]/ajax.php?act=LVZID',
        'way' => 1,
        'placeholder' => '在此输入链接,然后点击获取按钮！',
    ],
];
